version: '3.1'
services:
  fill_db:
    image: paua/sensorik-fill_db
    environment:
      fill_monogo_host: "192.168.178.58"
      fill_monogo_port: 27017
      fill_monogo_db: "bigChart"
      fill_monogo_pw: "Daten2018"
      fill_mongo_user: "root12"
      fill_website_port: 8080
      env: "PROD"
    ports:
      - 8080:8080
    
